version: '3.10'

services:
  rails-app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/workspace:cached
    environment:
      - CAPYBARA_SERVER_PORT=45678
      - SELENIUM_HOST=selenium
      - REDIS_URL=redis://redis:6379/1
    depends_on:
      - db
      - redis
      - selenium
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myapp_development
    ports:
      - "5432:5432"
  redis:
    image: redis:6
    ports:
      - "6379:6379"
  selenium:
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
